# Generated by Django 3.1.4 on 2021-01-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
