# Generated by Django 3.1.4 on 2021-02-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210202_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('jewelry', 'Jewelry'), ('produce', 'Produce'), ('clothing', 'Clothing'), ('yardsale', 'Yardsale'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
