# Generated by Django 3.1.4 on 2021-02-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='thumb',
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='no-image-found.png', upload_to=''),
        ),
    ]
